import { Geist, Geist_Mono } from 'next/font/google';
import 'bootstrap/dist/css/bootstrap.min.css';
import './globals.css';
import '../builder-registry';
import '../styles/custom.css';
import 'bootstrap-icons/font/bootstrap-icons.css';
import '@fortawesome/fontawesome-free/css/all.min.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

import ContextProvider from '../components/ContextProvider';

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body>
        <ContextProvider>{children}</ContextProvider>
      </body>
    </html>
  );
}